---

os: linux
services:
- docker

env:
  global:
  - NAMESPACE=informaticsmatters
  - IMAGE=im-mini-apps
  # Our CI/CD DOCKER username and password
  - secure: fsuRinijwlHy7iz+W5ttzRAnnhx/xmMCI7DUh3i65bQIj/XmIqQL9P80MOuUO+elOZzXUaqJMWFTTC9nCYDkmiq7RbKawBKAHPZqcTetYAbacvFJuQ3SPH0n1jbYunuIoTKkib1yAfBt5G/svOmsdaN/bVHA1F0fZeLfmQ51KCfD1XhpBNjxqteakKQqtmT5+T4APF0njR5H6rZ+ONXQMwOk+jp3s5tj8VAP3qdaIcB+rTLVXXj7LXtrcqCwbNL56QOX0fwLHIuW62MXIoM+tZrjvYpvaLyHwZoyK3SrjR60C21IsnLJyOo0mOFI362UTX9DV1GdcvSv8Wjm+faEPmNx1WwfFtt1tVqhOiZCR8Ub3Y0Rc4PG6esUraOoa48f+Cwv0HDIYVdeVi8i2FkGWoz6YfOwM3iZW9OVQRqv7UrWsUZiyauFb7iJiHI1PPIoN9vKfHtA3NgPDsPaa1YesLoqDIL9Hg5RpF96LvNGl98h2/Fug1suD8O4y+9NRL6NCdja6DcmhA5xWf5d/6NKfOwiHl/mxYHKhHyBnIOdkAObgdRnwfydRAxQbAFgcwewhESzKEx7E152I6i3El05aNL4pok9Ts9vg8MXYDUcL0UXEKRUAOF0P8C7ZGCl5oaBazPNccqj9V1NsJ5pLI0YQD1cQluHEQhGNf3qt9/rP4w=
  - secure: U8jqNlW/HS++NnUTVPCeOjBtu0KfkY5vv3mlvcl6faJy1C3n8UXHReR5IidEc2iQf4xEOnbl2Jhb8sy82zXhnk5e4/Ry/LVtoltBFSxG5kF89GPQGlCovt1kg5vdu+l9gRngsHk5OxUpp1gTGXV28Zne8dZZcZUrH3hZAUIns1CKIwinD8VfdhHE0q6xY/rx0b6cLJ0M52H3+iPI0EIuwSMKmaFOlDNIISnpfUIoaw95ziw1d9zOLSIcn1wRBto90afNd9Ormt2eLRb7LLnv01pZoxIq8eaWGgUUIFZTbpW+C1ZV2z6x9zNfH0aL2+DJueu5NUCpDpS6xXEbCQn72Fpcae1uLPXD0KYHl3/kNfPl7yIDMkW0w2c1foId+jSBCJjg/40z+lpkHUBlJmpr3imXov61B9D5ZYznmkSUWhl0SGNO8pZjUpIe0ZXix8CsAf1IYdaG1AJODGVZ+zPhjA2lJTNkAvcBaBe5y0dYioAF4JdyrtNDDMP3Qjh8KUib+3cdAekIWvviE+I/QOcM5izZ66oScMSmrSR4LiIYvX1D6TOfegSJL7mS/Kzvn8DpX3acPoGcCB8RlYfOWnIXfKtU6QL9PG2qctDvROoSm45pGJeqAT8EAYrvNUTkh8RitJGtKZlwL16KR7BG5wFmGET1zvGaYPBDDwgnNI4E3Cw=

stages:
- name: publish latest
  if: |
    branch = master
- name: test latest
  if: |
    branch = master
- name: publish tag
  if: |
    tag IS present
- name: publish stable
  if: |
    tag IS present \
    AND tag =~ ^([0-9]+\.){1,2}[0-9]+$

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:

  # Publish-stage jobs...
  # Every successful master build results in a latest image
  # and every tag results in a tagged image in Docker Hub.

  - stage: publish latest
    name: Latest Image
    script:
    # Build and push the pipelines-rdkit image and its sd-poster
    - docker build -t ${NAMESPACE}/${IMAGE}:latest .
    - docker push ${NAMESPACE}/${IMAGE}:latest

  - stage: publish tag
    name: Tagged Image
    script:
    # Build and push the pipelines-rdkit image and its sd-poster
    - docker build -t ${NAMESPACE}/${IMAGE}:${TRAVIS_TAG} .
    - docker push ${NAMESPACE}/${IMAGE}:${TRAVIS_TAG}

  - stage: publish stable
    name: Stable Image
    script:
    # Pull the corresponding pipelines-rdkit image tag and push it as 'stable'
    - docker pull ${NAMESPACE}/${IMAGE}:${TRAVIS_TAG}
    - docker tag ${NAMESPACE}/${IMAGE}:${TRAVIS_TAG} ${NAMESPACE}/${IMAGE}:stable
    - docker push ${NAMESPACE}/${IMAGE}:stable
